version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  generate docs:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          TZ: "Europe/London"
    environment:
      DEBUG: "*"
    resource_class: xlarge     
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: npm install
          command: |
            npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            sudo npm install -g lerna@6.6.1
            yarn install
      - run:
          name: pull Tymly monorepo
          command: git clone https://github.com/wmfs/tymly.git
      - run:
          name: sync Tymly monorepo
          command: |
            cd tymly
            npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            sudo npm install
            TYMLY_GITHUB_USER=$GIT_AUTHOR_NAME TYMLY_GITHUB_TOKEN=$GH_TOKEN npm run sync public-only
      - run:
          name: bootstrap Tymly monorepo
          command: |
            cd tymly
            sudo lerna clean --yes
            sudo lerna bootstrap -- --production
            sudo lerna link --force-local
      - run:
          name: generate docs
          command: |
            cd tymly/packages/tymly-doc-generator
            TYMLY_MONOREPO_PATH=/home/circleci/repo/tymly TYMLY_DOCS_OUTPUT_PATH=/home/circleci/repo npm run generate
      - run:
          name: deploy docs
          command: |
            git config --global user.name "$GIT_COMMITTER_NAME"
            git config --global user.email "$GIT_COMMITTER_EMAIL"
            echo "Building"
            sudo yarn docs:build
            echo "Deploying"
            cd ./docs/.vuepress/dist
            git init
            git add -A
            git commit -m "chore: deploy [skip ci]"
            git push -f https://${GIT_COMMITTER_NAME}:${GH_TOKEN}@github.com/wmfs/tymly-website.git master:gh-pages
workflows:
  version: 2
  manual:
    jobs:
      - generate docs:
          context:
            - docker-hub-creds
            - build-env-vars
          filters: 
            branches:
              only:
                - master
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - generate docs:
          context:
            - docker-hub-creds
            - build-env-vars
          filters: 
            branches:
              only:
                - master
