version: 2
jobs:
  generate docs:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: xlarge     
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: npm install
          command: sudo npm install -g lerna && npm install
      - run:
          name: pull Tymly monorepo
          command: git clone https://github.com/wmfs/tymly.git
      - run:
          name: sync Tymly monorepo
          command: |
            cd tymly
            npm install
            TYMLY_GITHUB_USER=$GIT_AUTHOR_NAME TYMLY_GITHUB_TOKEN=$GH_TOKEN npm run sync
      - run:
          name: bootstrap Tymly monorepo
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN && cd tymly && npm run bootstrap
      - run:
          name: generate docs
          command: |
            cd tymly/packages/tymly-doc-generator
            TYMLY_MONOREPO_PATH=/home/circleci/repo/tymly TYMLY_DOCS_OUTPUT_PATH=/home/circleci/repo npm run generate
      - run:
          name: deploy docs
          command: chmod +x scripts/deploy && ./scripts/deploy
  release:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: install
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: release
          command: npx semantic-release
workflows:
  version: 2
  generate and release:
    jobs:
      - generate docs:
          context:
            - docker-hub-creds
            - build-env-vars
          filters: 
            branches:
              ignore:
                - gh-pages
