version: 2
jobs:
  generate docs:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: pull Tymly monorepo
          command: git clone https://github.com/wmfs/tymly.git
      - run:
          name: sync Tymly monorepo
          command: |
            cd tymly
            TYMLY_GITHUB_USER=$GIT_AUTHOR_NAME TYMLY_GITHUB_TOKEN=$GH_TOKEN npm run sync
  release:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: install
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: release
          command: npx semantic-release
workflows:
  version: 2
  generate and release:
    jobs:
      - generate docs:
          context:
            - docker-hub-creds
            - build-env-vars
      - release:
          context:
            - docker-hub-creds
            - build-env-vars
          filters:
            branches:
              only: master
