version: 2
orbs:
  slack: circleci/slack@3.4.2
jobs:
  generate docs:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: xlarge     
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: npm install
          command: sudo npm install -g lerna && npm install
      - run:
          name: pull Tymly monorepo
          command: git clone https://github.com/wmfs/tymly.git
      - run:
          name: sync Tymly monorepo
          command: |
            cd tymly
            npm install
            TYMLY_GITHUB_USER=$GIT_AUTHOR_NAME TYMLY_GITHUB_TOKEN=$GH_TOKEN npm run sync
      - run:
          name: bootstrap Tymly monorepo
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN && cd tymly && npm run bootstrap
      - run:
          name: generate docs
          command: |
            cd tymly/packages/tymly-doc-generator
            TYMLY_MONOREPO_PATH=/home/circleci/repo/tymly TYMLY_DOCS_OUTPUT_PATH=/home/circleci/repo npm run generate
      - run:
          name: deploy docs
          command: chmod +x scripts/deploy && ./scripts/deploy
      - slack/notify:
          include_job_number_field: false
          include_project_field: false
          color: '#C9F0E9'
          message: "Look at that! Tymly Website has been built. :tada:"
      - slack/status:
          include_job_number_field: false
          include_project_field: false
          fail_only: true
          failure_message: "Ow! Tymly Website failed check the logs! :skull:"
workflows:
  version: 2
  generate and release:
    triggers:
      - schedule:
          cron: "43 7 * * *"
          filters:
            branches:
              only:
                - exactlyaron/ch4719
    jobs:
      - generate docs:
          context:
            - docker-hub-creds
            - build-env-vars
          filters: 
            branches:
              ignore:
                - gh-pages
