#!/usr/bin/env bash

git config --global user.name "$GIT_COMMITTER_NAME"
git config --global user.email "$GIT_COMMITTER_EMAIL"
npm run docs:build
cd docs/.vuepress/dist
git init
git add -A
git commit -m "deploy"
git push -f https://${GIT_COMMITTER_NAME}:${GH_TOKEN}@github.com/wmfs/tymly-website.git master:gh-pages